### ISSUE TITLE
Implement Config Parser for YAML Rules

### ISSUE THREAD

**Issue by mecattaf** [mecattaf/smart-tiling#6]
## Context
The smart-tiling system needs to load configuration from YAML files. Currently, `main.py` references `config.parser.load_config()` but the module doesn't exist, using a mock fallback instead.

## Current State
- `/smart_tiling/config/parser.py` - Does not exist
- Mock function in `main.py` returns empty dict
- No YAML parsing capability

### 1. Create Config Parser Module
Create `/smart_tiling/config/parser.py` with:

#### `load_config(path: Optional[str]) -> Dict[str, Any]`
- Accept optional path to YAML file
- If no path provided, check default locations:
  - `~/.config/smart-tiling/rules.yaml`
  - `~/.config/smart-tiling/config.yaml`
  - `/etc/smart-tiling/config.yaml`
- Return parsed configuration dict or empty dict if no config found
- Handle file not found gracefully (return empty dict, don't crash)

#### `parse_yaml_file(path: str) -> Dict[str, Any]`
- Load and parse YAML file
- Handle YAML syntax errors with clear error messages
- Return parsed dictionary

### 2. Configuration Structure
The parser should expect this structure:
```yaml
rules:
  - name: "Neovim Terminal"
    parent:
      app_id: ["neovim", "nvim"]
      class: ["Neovim"]
    child:
      app_id: ["kitty", "alacritty", "foot"]
    actions:
      - set_mode: v after
      - place: below
      - size_ratio: 0.333
      - inherit_cwd: true
      - preserve_column: true

settings:
  debug: false
  rule_timeout: 10
```

### 3. Dependencies
- Add PyYAML to dependencies (already in setup.cfg)
- Use standard library for path operations

### 4. Error Handling
- Missing file: Return empty config (not an error for 0.0.1)
- Invalid YAML: Print error to stderr, return empty config
- Invalid structure: Accept it for now (schema validation is separate issue)

## Success Criteria
- [ ] Config parser module exists and loads YAML files
- [ ] Default config paths are checked if no path provided
- [ ] YAML syntax errors are handled gracefully
- [ ] main.py can import and use real config loader
- [ ] Empty/missing config doesn't crash the program

## Out of Scope
- Schema validation (separate issue)
- Hot-reloading of config
- Config file watching
- TOML support
- Environment variable expansion

## Testing Requirements
Create `/smart_tiling/tests/test_config_parser.py` with tests for:
- Loading valid YAML file
- Handling missing file
- Handling invalid YAML syntax
- Default path resolution
- Empty config handling
